name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        SETUP: ['/cvmfs/sw.hsf.org/key4hep/setup.sh', '/cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh']
    steps:
    - uses: cvmfs-contrib/github-action-cvmfs@v3.1

    - name: Checkout
      uses: actions/checkout@v3

    - name: Download test inputs
      run: |
        wget http://lreichen.webtest.cern.ch/test.slcio

    - name: Start container
      run: |
        docker run \
          -it --name CLDConfig_CI \
          -v ${{ github.workspace }}:/CLDConfig \
          -v /cvmfs:/cvmfs:shared \
          -d ghcr.io/aidasoft/centos7:latest /bin/bash

    - name: Run tests (pytest)
      run: |
        docker exec CLDConfig_CI /bin/bash -c 'source ${{ matrix.SETUP }};
          cd CLDConfig;
          pytest;
        '
